{
    'c2fc02': 'articles/python-detecting-star-imports',
    'b6b144': 'articles/gsoc/introduction',
    'cbb8a3': 'articles/gsoc/git-understanding-old-branches',
    '61f5b6': 'articles/gsoc/cython-debugger-mac',
    'fb9b1c': 'articles/gsoc/macos-compiling-openmp-libraries',
    'd74ad2': 'articles/gsoc/design-01-data-layer-separation',
    '11f082': 'articles/gsoc/design-02-data-structures',
    '94234a': 'articles/gsoc/developers-guide-sphinx',
    'c0417a': 'articles/gsoc/design-tensor-product-type',
    'db41b3': 'articles/gsoc/fsanitize-cython',
    '34505b': 'articles/gsoc/design-data-layer-to-dispatcher',
    'ffb8a3': 'articles/gsoc/final-post',
    '404ffd': 'articles/teaching/general-fourier-series/part-0-introduction',
    '080743': 'articles/teaching/general-fourier-series/part-1-linear-algebra',
    'ce0047': 'articles/teaching/general-fourier-series/part-2-making-new-series',
    'a02a84': 'articles/teaching/general-fourier-series/part-3-comparing-series-expansions',
    'ac256b': 'articles/github-actions-first-tricks',
    '0efda1': 'articles/python-tuple-setitem',
    'cf7dcd': 'articles/python-scoping',
    # '3e4e9c': 'articles/qiskit-singleton-gates',
    '25ef50': 'articles/complex-signed-zeroes',
    'e01223': 'articles/relicense-cc-by',
}
